spring:
 application:
  name: activityservice
 data:
  mongodb:
   uri: mongodb://localhost:27017/aiactivityfitness
   database: aiactivityfitness

server:
 port: 8081

eureka:
 client:
  service-url:
   defaultZone: http://localhost:8082/eureka
